### ISSUE TITLE
Mob Spawning

### ISSUE THREAD

**Issue by PatheticMustan** [KryptoCrash/TheWools#1]
We need to figure out how to spawn mobs with the java Spigot API.

Goals:
1. Spawn a zombie, skeleton, and spider.
2. Spawn a zombie with armor, and a sword.
3. Spawn a zombie with enchanted armor, and an enchanted sword.

**Comment by 00100000** [comment]
Kevin u dummy this is your job REEEE

**Comment by 01-1** [comment]
... the last edit was 10 months ago

**Comment by PatheticMustan** [comment]
maybe we should archive the repo

**Comment by 00100000** [comment]
sounds like a good idea
